import sys
sys.path.insert(0, '.')

from ml.persona.engine import generate_message
from ml.mirror.scorer import score_message

lead = {
    "name": "Rahul Sharma",
    "company": "TechCorp",
    "role": "CTO",
    "persona": "dev"
}

print("Generating message...")
result = generate_message(lead)
message = result["message"]
print(f"Message generated by: {result['persona_name']}\n")

print("Running MIRROR score gate...")
score_result = score_message(lead, message, threshold=60)

print(f"\n{'='*50}")
print(f"✅ APPROVED" if score_result["approved"] else "❌ BLOCKED")
print(f"Final Score: {score_result['score']}/100")
print(f"Attempts: {score_result['attempts']}")
print(f"Reaction: {score_result['reaction']}")
print(f"\nFinal Message Sent:\n{score_result['final_message']}")